export const SIGNUP_INPUT_LIST = [
  {
    id: 1,
    title: '이메일',
    name: 'email',
    type: 'text',
    placeholder: '예: wisely@wisely.com',
    check: 'emailCheck',
    errorMsg: '이메일 형식으로 입력해 주세요',
  },
  {
    id: 2,
    title: '비밀번호',
    name: 'password',
    type: 'password',
    placeholder: '비밀번호를 입력해주세요',
    check: 'passwordCheck',
    errorMsg: '영문 대소문자/숫자/특수문자 중 2가지 이상 조합. 10자~16자',
  },
  {
    id: 3,
    title: '비밀번호확인',
    name: 'passwordConfirm',
    type: 'password',
    placeholder: '비밀번호를 한번 더 입력해주세요',
    check: 'passwordAgainCheck',
    errorMsg: '동일한 비밀번호로 입력해 주세요',
  },
  {
    id: 4,
    title: '이름',
    name: 'userName',
    type: 'text',
    placeholder: '이름을 입력해주세요',
  },
  {
    id: 5,
    title: '성별',
    name: 'gender',
  },
  {
    id: 6,
    title: '휴대전화',
    name: 'phoneNumber',
    type: 'number',
    placeholder: '예: 01012345678',
  },
  {
    id: 7,
    title: '생년월일',
    name: 'birth',
    type: 'number',
    placeholder: '예: 950105,  6자리 입력',
  },
  {
    id: 8,
    title: '주소',
    name: 'adress',
    type: 'text',
    placeholder: '도로명 주소로 입력해주세요',
  },
];
